# Generated by Django 3.2.2 on 2021-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_feed',
            name='news',
            field=models.TextField(default=1.0),
            preserve_default=False,
        ),
    ]
