# Generated by Django 3.2.2 on 2021-05-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_news_feed_newsfeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='news',
            new_name='body',
        ),
    ]
