# Generated by Django 3.2.2 on 2021-05-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_session_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
    ]
