# Generated by Django 3.2.2 on 2021-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_session_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
