# Generated by Django 3.2.2 on 2021-05-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_session_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
